services:
  jaeger:
    image: jaegertracing/jaeger:latest
    container_name: jaeger
    ports:
      - "16686:16686"   # Web UI
      - "4318:4318"     # OTLP HTTP
      # - "4317:4317"     # OTLP gRPC
      # - "5778:5778"     # Config server
      # - "9411:9411"     # Zipkin compatible
    restart: unless-stopped

